# Generated by Django 3.0.5 on 2023-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subject_semester_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_file',
            name='document',
            field=models.FileField(upload_to='media/profile_pic'),
        ),
    ]
