# Generated by Django 3.0.5 on 2023-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230425_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_file',
            name='document',
            field=models.FileField(upload_to='document/files'),
        ),
    ]
