# Generated by Django 3.0.5 on 2023-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230425_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_file',
            name='document',
            field=models.FileField(upload_to='media/'),
        ),
    ]
