# Generated by Django 3.0.5 on 2023-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230425_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_file',
            name='document',
            field=models.ImageField(upload_to='media/profile_pic'),
        ),
    ]
