# Generated by Django 3.0.5 on 2023-04-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230425_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_file',
            name='document',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
