# Generated by Django 3.0.5 on 2023-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20230425_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
