# Generated by Django 3.0.5 on 2023-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='designation',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
