# Generated by Django 3.0.5 on 2023-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_about_us_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='admin_profile_pic',
            field=models.ImageField(default=None, upload_to='media/profile_pic'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='profile',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
