# Generated by Django 4.2.1 on 2023-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_chatmessage_qaresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enr',
            field=models.CharField(default='E20301235600007', max_length=50),
        ),
    ]
