# Generated by Django 4.2.1 on 2023-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_busdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsotel_code', models.CharField(max_length=50)),
                ('hsotel_for', models.CharField(max_length=50)),
                ('hsotel_fair', models.IntegerField()),
                ('hsotel_type', models.CharField(max_length=50)),
            ],
        ),
    ]
