# Generated by Django 4.2.1 on 2023-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_hosteldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteldetails',
            name='hsotel_code',
        ),
        migrations.AddField(
            model_name='hosteldetails',
            name='hostel_availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hosteldetails',
            name='hostel_room_bed',
            field=models.IntegerField(default='6'),
        ),
        migrations.AddField(
            model_name='hosteldetails',
            name='hsotel_block',
            field=models.CharField(default='block A', max_length=50),
        ),
        migrations.AlterField(
            model_name='hosteldetails',
            name='hsotel_for',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='hosteldetails',
            name='hsotel_type',
            field=models.CharField(default='Non-AC', max_length=50),
        ),
    ]
