# Generated by Django 4.2.1 on 2023-07-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_hosteldetails_hsotel_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosteldetails',
            old_name='hsotel_block',
            new_name='hostel_block',
        ),
        migrations.RenameField(
            model_name='hosteldetails',
            old_name='hsotel_fair',
            new_name='hostel_fair',
        ),
        migrations.RenameField(
            model_name='hosteldetails',
            old_name='hsotel_for',
            new_name='hostel_for',
        ),
        migrations.RenameField(
            model_name='hosteldetails',
            old_name='hsotel_type',
            new_name='hostel_type',
        ),
    ]
