# Generated by Django 4.2.1 on 2023-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_attendance_attendancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
